### PR TITLE
Set image size metadata when uploading images to S3

### PR DESCRIPTION
**Pull request by Dantemss**
Will be used by Rex prerendering at some point

### CODE REVIEW

**Comment by therealmarv** [comment]
(all only my opinion) The `copy_resources_s3.py` should really only copy files to s3 and should not have other logic inside.
Why: For debugging purposes and seperate concerns. For example (not sure we ever want this):
* maybe we want a local rex-preview of Enki with the right image dimensions served from the local file system
* or we want to debug why a file height and width could not be parsed (the s3 copy process will not be run on local enki)

The image sizes should be a new field in the internal used json metadata file. There should be two new fields for height and width computed and added in [`checksum_resource.py` here](https://github.com/openstax/enki/blob/c3d752aa05e0181403507840ff6bd5769b621eda/bakery-src/scripts/checksum_resource.py#L33)

At the end this new height and width field in the metadata json can be parsed and added to the s3 header in `copy_resources_s3.py`

Another thought I have:
I think loading every resource image with Pillow into memory will make image heavy book pipelines take much longer. It's just a gut feeling and I have not benchmarked it in any way.
Assuming we have mostly JPEG, PNG (maybe even GIF?) images there is also a direct way to read the pixel width and height from the image headers (bits and bytes) without processing the image as a whole into Pillow. A library which can do this (not sure if it is the best, needs research) is e.g. https://pypi.org/project/imagesize/

Here is some benchmark comparison of image header direct parsing and using Pillow: https://github.com/shibukawa/imagesize_py#benchmark

**Comment by Dantemss** [comment]
OK thanks. I can move the code. The advantage of putting it in the S3 file was that the PIL stuff could happen in the S3 upload workers so in theory there would be some parallelization there. But I agree there could be better places for it.

As for the performance, getting the size of a (small) image seems to take 30 milliseconds for me. But the wisdom seems to be that Pillow's open() method does not read the whole image so the size shouldn't matter much.

**Comment by therealmarv** [comment]
I'll also took a closer look at the benchmark I've linked [above](https://github.com/shibukawa/imagesize_py#benchmark). For him it's taking 9 seconds longer for 100,000 images with 125kb size. We have a lot of images in books but not 100K images 😅 It seems you are right that Pillow open does not load the whole image. We can definitely afford 9 seconds longer runtime in the pipeline! :)

The move of the code into `checksum_resource.py` is also the more important point.

**Comment by Dantemss** [comment]
Turns out Pillow does not support svg images... which is not a problem for most SVGs since they don't have a size but the test has one with width and height set in the SVG itself which should probably output those. Let me try the lib you mentioned

**Comment by Dantemss** [comment]
@therealmarv I made the changes you requested and finally managed to fix the tests so I believe this is ready for another look

**Review by therealmarv — APPROVED** [review]
Worked well on internal tests.
It's good that the library [imagesize](https://pypi.org/project/imagesize/) works well on common images we use and SVGs.

**Pull request merged**
