### PR TITLE
Update the Commandline Interface

### PR DESCRIPTION
**Pull request by philschatz**
## Reviewers: Feel free to approve or remove yourself as a reviewer if you're okay with this change in workflow

Questions:

- [x] are there better names for the CLI args? like `--clean` instead of `--clean-data-dir`

---

The current CLI arguments are positional and environment variables. This changes the script in the following ways:

- CLI arguments are named
- the script can be executed from any directory (no need to `cd /path/to/enki`)
- the script can be symlinked
- additional helper arguments were added (e.g. `--clear-data`, `--start-at`, `--sideload-book`)

This also should allow folks to "install" the script using the [basher package manager](https://github.com/basherpm/basher) for shell scripts

```
enki --help

    Required Arguments:

        --command all-git-pdf       Command/Step to run. Can be a shortcut like all-git-pdf or all-git-web)

    Optional Arguments:

        --help                      This help page
        --version                   The version of enki

        --clear-data                Remove the date directory before running
        --keep-data                 Keep the data directory before running
        --data-dir <path>           Path to store temporary files
        --dotenv-file <path>        Path to dotenv file (for GitHub credentials)

        --style <name|"default">    A recipe style to use or "default" to use what is defined in the repo
        --ref <branch|tag|@commit>  Which version of the book to build
        --repo osbooks-mybook       The name of the repo. Can be "owner/name" if the owner is not openstax
        --book-slug calculus-vol-1  Which book (identified by slug) to build

        --start-at git-bake         Step to start at (also sets --keep-data)
        --stop-at git-bake          Step to stop at

        --sideload-book <path>      A local path to a cloned git repo instead of fetching from GitHub
        --sideload-recipes <path>   Path to a locally cloned cookbook

    Status:

        GitHub Credentials? yes
        Cache folder location: /home/phil/.local/share/enki-data
        Dotenv file location: /home/phil/git/openstax/enki/.env
        Docker image name: enki

        Repo: 
        Slug: 
        Ref: 
        Style: 
```

# TODO

- [x] add `./cli.sh` deprecations and sleep 60 and some noises

### CODE REVIEW

**Review by Stackblocks — APPROVED** [review]
Looks good from my point of view. I like how much more parsable the commands are with the new `./enki --command all-git-pdf --repo "x" --book-slug "y"` arrangement. 

Definitely excited about `--clean-data-dir` saving me from having to go in and manually delete the old directory to prep the way for the new one.

(And I feel like I'll mistype the repo & slug much less frequently when they're separated vs being a long string.)

Interested to hear what the dev side have to say about it.

**Review by TylerZeroMaster — APPROVED** [review]

**Review by m1yag1 — APPROVED** [review]

**Review by sparksam — APPROVED** [review]

**Comment by m1yag1** [comment]
I ran the following command:

```
./enki --repo osbooks-college-physics-bundle  --data-dir ./data/ --command all-git-pdf
```
This initially didn't work because I didn't provide some other values. It wasn't exactly clear which value I missed so I experimented by adding them one at a time. Each time it was a bit difficult to tell which param I had left off that caused an error. For example:

```
loning into '/data/fetched-book-group'...
remote: Repository not found.
fatal: repository 'https://github.com/openstax/.git/' not found
++ [docker-entrypoint.sh:33] die 'ERROR: could not run [git clone --depth 1 https://github.com/openstax/.git --branch main /data/fetched-book-group]' 112
++ [docker-entrypoint.sh:29] yell 'ERROR: could not run [git clone --depth 1 https://github.com/openstax/.git --branch main /data/fetched-book-group]'
++ [docker-entrypoint.sh:26] echo -e '/dockerfiles/docker-entrypoint.sh: ERROR: could not run [git clone --depth 1 https://github.com/openstax/.git --branch main /data/fetched-book-group]'
/dockerfiles/docker-entrypoint.sh: ERROR: could not run [git clone --depth 1 https://github.com/openstax/.git --branch main /data/fetched-book-group]
++ [docker-entrypoint.sh:30] exit 112
```
The above error is because I didn't have a book slug.

**Review by kswanson33 — APPROVED** [review]

**Comment by philschatz** [comment]
Thanks @kswanson33 ! Yeah, the `--gitref main --recipe default` really should be optional. They're in there because archive books still need them but I'll make both of them optional when archive books are removed from enki (coming up soon)

**Comment by philschatz** [comment]
I made a couple small changes to the CLI arguments:

- `--clean-data-dir` is now flipped to be `--keep-data` or `--clear-data`

Here are all the commandline arguments:

```
enki --help

    Required Arguments:

        --command all-git-pdf       Command/Step to run. Can be a shortcut like all-git-pdf or all-git-web)

    Optional Arguments:

        --help                      This help page

        --clear-data                Remove the date directory before running
        --keep-data                 Retain the data directory before running
        --data-dir <path>           Path to store temporary files
        --dotenv-file <path>        Path to dotenv file (for GitHub credentials)

        --style <name|"default">    A recipe style to use or "default" to use what is defined in the repo
        --ref <branch|tag|@commit>  Which version of the book to build
        --repo osbooks-mybook       The name of the repo. Can be "owner/name" if the owner is not openstax
        --book-slug calculus-vol-1  Which book (identified by slug) to build

        --start-at git-bake         Step to start at (also sets --keep-data)
        --stop-at git-bake          Step to stop at

        --sideload-book <path>      A local path to a cloned git repo instead of fetching from GitHub
        --sideload-recipes <path>   Path to a locally cloned cookbook

    Status:

        GitHub Credentials? yes
        Cache folder location: 
        Dotenv file location: /home/phil/git/openstax/enki/.env
        Docker image name: enki

        Repo: 
        Slug: 
        Ref: 
        Style: 
```

**Pull request merged**
