### PR TITLE
change URLs to CE account

### PR DESCRIPTION
**Pull request by dtwilliamson**

### CODE REVIEW

**Review by m1yag1 — APPROVED** [review]

**Comment by m1yag1** [comment]
This is great! We'll need to coordinate the merging of this PR with all the others. I'll update the auto-migrate-corgi pipeline to generate a pipeline file from this enki branch.

**Comment by dtwilliamson** [comment]
I will wait to merge it.

**Comment by m1yag1** [comment]
OK the [PR](https://github.com/openstax/ce-pipelines/blob/migrate-swarm/pipelines/auto-migrate-corgi.yml#L35-L39) on the ce-pipelines side has been updated. I'm going to kick off the deploy to see what happens.

**Comment by m1yag1** [comment]
The new pipeline was created here: https://concourse-v7.openstax.org/teams/CE/pipelines/corgi-migrate-staging

**Pull request merged**
